### PR TITLE
5.0.d

### PR DESCRIPTION
**Pull request by fecabianchi**
Hi, i tried this on 5.0.d and is not working i created the GROUP_SITE_CREATORS and add myself but create site button still hidden. can you help me?

### CODE REVIEW

**Comment by douglascrp** [comment]
@fecabianchi The name of the group should be "SITE_CREATORS".
The "GROUP_" part of the name is internal, and Alfresco uses it.
So, you are creating your group, use only "SITE_CREATORS", and I think it will work.

**Comment by alahwany** [comment]
Hello,
can you please give me the AMP files to install it on alfresco 5.0.0 d community version ?

**Comment by jpotts** [comment]
Sure, here you go.

**Comment by jpotts** [comment]
alahwany, I created a release for the 5.0.d branch and attached the built AMPs to it.

**Pull request closed without merging**
